# Generated by Django 3.0.3 on 2020-05-12 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinnerplatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDinn', models.CharField(max_length=64)),
                ('smallDinn', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('largeDinn', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastaName', models.CharField(max_length=64)),
                ('pricePasta', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smallPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('largePrice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saladName', models.CharField(max_length=64)),
                ('priceSalad', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSub', models.CharField(max_length=64)),
                ('smallSub', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('largeSub', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='initiated', max_length=64, null=True)),
                ('cart_item', models.CharField(max_length=64)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('extras', models.CharField(blank=True, max_length=512, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('special_status', 'Can read all books')],
            },
        ),
    ]
