# Generated by Django 3.0.3 on 2020-05-12 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200513_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orderhistory'),
        ),
    ]
