# Generated by Django 3.0.3 on 2020-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200513_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
    ]
