# Generated by Django 3.0.3 on 2020-05-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200513_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.CharField(default='notdelivered', max_length=512),
        ),
    ]
